function [Q, T] = schur2(A)
% SCHUR2 Ordered Schur decomposition of a 2x2 quaternion matrix via the 4x4
% complex adjoint; eigenvalue classes grouped by modulus (largest first).
[Q, T] = schur(adjoint(A));
[Q, ~] = ordschur(Q, T, groupByValue(abs(diag(T))));
Q = quaternion( ...
    real(Q([1,2], [1,3])), ...
    imag(Q([1,2], [1,3])), ...
    -real(Q([3,4], [1,3])), ...
    imag(Q([3,4], [1,3])) ...
);
T = Q' * A * Q;
end
